### ISSUE TITLE
Разобраться с Sass ниже описание

### ISSUE THREAD

**Issue by gerasart** [sergosound/Test#12]
- [x] Установить SASS ( в особенности SCSS ) - http://www.creative-seo.ru/blog/sass-ustanovka-na-windows/
- [x] Переделать стили для шаблона что делаешь в SCSS
-в особенности понять как работает import
-разделить стили на разные файлы логические
- [x] Команды - https://sass-scss.ru/documentation/ispolzovanie_sass/

**Comment by sergosound** [comment]
То есть весь css файл переписать в scss?
